### ISSUE TITLE
install-script does not work when proxy is required

### ISSUE THREAD

**Issue by joebride** [kevingstewart/simple-dehydrated-acme-f5#2]
Hallo!

#### Description  
install.sh does not work when URLs must be reached via http-proxy.  
 E.g. acmeclient_url="https://raw.githubusercontent.com/dehydrated-io/dehydrated/master"

#### Expected Result 
Please provide a install-script which supports also installation via proxy.
Find below a potential solution.

Many Thanks!

#### Simple Solution
```
proxy=http://<ip-of-proxy>:<tcp-port-of-proxy>

curl --proxy $proxy -s ${acmeclient_url}/dehydrated -o /shared/acme/dehydrated && chmod +x /shared/acme/dehydrated
curl --proxy $proxy -s ${f5acmehandler_url}/f5acmehandler.sh -o /shared/acme/f5acmehandler.sh && chmod +x /shared/acme/f5acmehandler.sh
curl --proxy $proxy -s ${f5acmehandler_url}/f5hook.sh -o /shared/acme/f5hook.sh && chmod +x /shared/acme/f5hook.sh
curl --proxy $proxy -s ${f5acmehandler_url}/config -o /shared/acme/config
```

**Comment by kevingstewart** [comment]
Thanks for catching this. I have updated the install.sh to allow for a --proxy argument so user doesn't have to edit the script.

By the way, the main project has moved to: https://github.com/f5devcentral/kojot-acme

I'm keeping this local repo for testing. Thanks!
